### ISSUE TITLE
Convert from miles to light-seconds

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#10]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

It's not quite metric, but it might be helpful to convert distances to light-seconds

See `distanceMap` in [conversion_helper.js](../tree/master/src/conversion_helper.js) to get started

**Comment by simonstaton** [comment]
Working on this now, Hacktoberfest ;)

**Comment by cannawen** [comment]
Amazing, feel free to reach out if you get stuck! :)
