### ISSUE TITLE
Feature request: Add unit `qt` = 1/4 gallon

### ISSUE THREAD

**Issue by nalinbhardwaj** [cannawen/metric_units_reddit_bot#109]
## Issue description

Add unit quarters, with alias qt which denotes a quarter gallon. Very similar to the existing gallon unit, can be copied from [here](https://github.com/cannawen/metric_units_reddit_bot/blob/master/src/conversion_helper.js#L464)(just modify the conversion factor)
## Relevant links

[Reddit comment thread](https://www.reddit.com/r/metric_units/comments/73edn2/constructive_feedback_thread/dopvchb/)

**Comment by 123survesh** [comment]
Hi @nalinbhardwaj I would like to work on this issue

**Comment by nalinbhardwaj** [comment]
@123survesh I’m sorry, I think we’re going to have to close this issue. Since quarter is a very common keyword, I think the false positives would much outweigh the real conversions. It’s best to leave it unfixed.

I’m sorry I didn’t realize this when making the issue, you can take some other issue tagged with “help wanted”.

**Comment by 123survesh** [comment]
yep cool :+1:
