### ISSUE TITLE
Scan the r/homebrewing thread and post constructive feedback in r/metric_units

### ISSUE THREAD

**Issue by nalinbhardwaj** [cannawen/metric_units_reddit_bot#112]
## Issue description

Recently, r/homebrewing was considering banning u/metric_units, to gain consensus etc., they made a thread [here](https://www.reddit.com/r/Homebrewing/comments/77f81m/metric_bot/) discussing the pros and cons of having the bot. There are 195 comments in the thread, so it should be a fairly large job to go through the comments and extract useful feedback/bugs. Post this back into the [Constructive Feedback thread](https://www.reddit.com/r/metric_units/comments/73edn2/constructive_feedback_thread/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=metric_units).

## Work

- Read through comments on the [r/homebrewing post](https://www.reddit.com/r/Homebrewing/comments/77f81m/metric_bot/)
- Extract useful constructive feedback, features that can be implemented, bugs etc.
- Post each of those in the [r/metric_units Constructive feedback thread](https://www.reddit.com/r/metric_units/comments/73edn2/constructive_feedback_thread/)

Note to @cannawen : Can we have a `non-coding` or similar tag for issues like this one? Is it even sensible to make this issue here?

**Comment by cannawen** [comment]
I don't see too much constructive feedback there, it's more of a vote yes/no thing. One general piece of feedback from there and other sources is 5% might be a bit too much to round, we can try to play with the numbers to something more precise. Should be a quick change but then we need to fix all our tests lol

Sure, you can add a non-coding tag if you feel like it makes sense :)

**Comment by nalinbhardwaj** [comment]
Yep, closing this @cannawen most comments I’ve scanned are not really constructive.
