### ISSUE TITLE
Move documentation to /docs folder

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#116]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

## First timers only
This issue is reserved for anyone who has **never** made a pull request to Open Source Software. If you are not a first timer, we would still love your help! Please see our other open issues :) 

[Read our New to OSS guide](https://github.com/cannawen/metric_units_reddit_bot/blob/master/NEW-TO-OSS.md) for an overview of what to expect
### IMPORTANT: Comment below if you would like to volunteer to tackle this issue.

---

## Recommended experience
- Some familiarity with basic markdown syntax
- No programming required to complete this task

## Time estimate
30-60 minutes

## The problem
Our project is getting cluttered with all this documentation at the top-level directory. Let's do some cleanup, and move all documentation into some subdirectories!

## Instructions
Ready? Let's get started!

1. Fork this repository ([detailed instructions](https://guides.github.com/activities/forking/#fork))
2. Clone your fork ([detailed instructions](https://guides.github.com/activities/forking/#clone))
3. Open the source code folder, and create two new folder called "docs" and ".github"
4. Move "CONTRIBUTING.md" "ISSUE_TEMPLATE.md", and "PULL_REQUEST_TEMPLATE.md" into the `.github` directory ([see why here](https://github.com/blog/2111-issue-and-pull-request-templates))
4. Move all other documentation into the "docs" folder, except for the README.
5. Go through all the documentation, and update any broken links (for example, the README must point to `./docs/CONTRIBUTING.md` instead of `./CONSTRIBUTING.md`)
6. Commit the changes with a descriptive git commit message
7. Push your changes back to github, and click around the documentation starting from `https://github.com/{{your-github-username}}/metric_units_reddit_bot` to make sure your links work
8. Make a pull request back to the main repository ([detailed instructions](https://guides.github.com/activities/forking/#making-a-pull-request))  
OPTIONAL: Don't forget to [give yourself credit](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md#add-yourself-to-the-contributors-list)! Thank you for contributing to metric_units bot! 
9. Wait for your PR to be reviewed by a maintainer, and address any comments they may have

## Step 10: YOUR CHANGE GETS MERGED!! Party!!!

**Comment by kritisingh1** [comment]
I am taking this up!

**Comment by cannawen** [comment]
Hey @kritisingh1 thanks for volunteering, but it looks like you are overqualified for this issue :( 

It's meant for first-time OSS contributors to get their feet wet, and it looks like you already have a solid grasp on how to make a PR! :D Thanks for your interest though

**Comment by kritisingh1** [comment]
Hi @cannawen ! Thanks for appreciation. I was about to submit a pull request. No worries. I am leaving it then  :)

**Comment by mayankagarwal2402** [comment]
Hi @cannawen. First time OSS contributor here. I would like to volunteer for this issue.

**Comment by cannawen** [comment]
Issue assigned to you, thanks for volunteering!
