### ISSUE TITLE
Change "version" string to "age" string in subreddit /r/totallynotrobots

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#12]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion. 

When it finds itself in [/r/totallynotrobots](https://www.reddit.com/r/totallynotrobots/comments/72u81b/i_very_much_enjoy_cracking_open_a_cold_one_with/dnlq0ag/), metric bot disguises itself as human because well... of course it's not a robot.

That being said, all humans have ages, whereas robots have version numbers. So this story is to change "v0.10.1" in metric bot's footer to  say "age0.10.1"

See [reply_maker.js](https://github.com/cannawen/metric_units_reddit_bot/blob/master/src/reply_maker.js) to get started!

**Comment by nitinkgp23** [comment]
I am picking this up :)

**Comment by cannawen** [comment]
Sounds good! Let me know if you need any assistance :)
