### ISSUE TITLE
Create personality response for "cute bot"

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#16]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion. What makes it sassy? The bot sometimes replies to comments like "good bot" and "bad bot" with its personality module.

This story is to give the bot even more personality! It should also reply to comments like "cute/adorable/kawaii bot" with even more cuteness and/or flirtation.

Possible replies:
`Stop it, you're making me blush!`
`So... do... you want to grab a drink later? ^blush`
...and anything else you feel is appropriate. Feel free to use lots of Japanese emoticons (◕‿◕✿)

See [personality.js](../tree/master/src/personality.js) and [personality-test.js](../tree/master/test/personality-test.js) to get started.

Leave a comment if you would like to take this on!

**Comment by chazzlabs** [comment]
I'd be happy to pick this one up.  😃

**Comment by cannawen** [comment]
Sweet, thank you! Let me know if you run into any problems :)

**Comment by softban** [comment]
If you're not already using it, https://api.ai/, would make this very easy & robust. 🍻

**Comment by cannawen** [comment]
Thanks for the link @softban , I put a story into the [icebox](https://www.pivotaltracker.com/story/show/151576337), perhaps for v2 of the bot!
