### ISSUE TITLE
Convert "pecks" to litres

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#17]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

I have no idea who would use pecks (other than peter piper, who picked a peck of pickled peppers...) but if someone ever does, it should be converted to something less silly! 

See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion (and note you can leverage the helper function `volumeMap()` to convert to metric volume units)

Leave a comment if you would like to take this on!

**Comment by miporto** [comment]
Hi, I would like to work on this issue!

**Comment by cannawen** [comment]
Sure thing, thanks! Let me know if you need any assistance :)

**Comment by miporto** [comment]
Hi! Just checking in. I already implemented the code, just waiting to October 1 to commit and make the PR 😁

**Comment by cannawen** [comment]
Sweet, looking forward to merging it in! :D

**Comment by cannawen** [comment]
Closed in #23
