### ISSUE TITLE
"pound-force" should be converted to Newtons

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#29]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

**Enhancement request:** "pound-force" units should be converted to Newtons. 
See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion

**Recommended skills:** Basic javascript & basic regular expressions
**Estimated time:** 30 minutes

Comment below if you would like to take on this task!

**Comment by winglian** [comment]
I'll take this one on

**Comment by cannawen** [comment]
Amazing! Feel free to reach out if you need any assistance :)
