### ISSUE TITLE
Bot converts string from middle of url

### ISSUE THREAD

**Issue by Xavion3** [cannawen/metric_units_reddit_bot#3]
See [this comment](https://www.reddit.com/r/feedthebeast/comments/6z896u/what_mod_add_this_text_on_the_top_right_corner_of/dmtbdnt/), imgur album id was `62lbS`and the bot interpreted that as a measurement. This is very rare most likely, and markdown parsing could be tricky, but is a bug.

**Comment by cannawen** [comment]
Fixed in v0.8.2 by ignoring numbers starting with `/`. Thanks for reporting the issue!
