### ISSUE TITLE
"troy ounces" should be converted to metric weights

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#30]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

**Enhancement request:**
Troy ounces are often used in precious metal subreddits, and they are different from regular ounces.
1) When the bot sees "troy ounces" it should be converted to metric weights.
2) When the bot sees "ounces" in a precious metal subreddit (/r/silverbugs or /r/pmsforsale) then it should convert as troy ounces.

See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion. You can consider using a "preprocess" step to convert all text mentions of "ounces" to "troy ounces" when appropriate

**Recommended skills:** Basic javascript & basic regular expressions
**Estimated time:** 60 minutes

Comment below if you would like to take on this task!

**Comment by eliotw** [comment]
Hi, I would be interested in taking this issue.

**Comment by cannawen** [comment]
Awesome, thank you! Let me know if you need any help :)
