### ISSUE TITLE
Acres should be converted to km^2, hectares, or m^2 

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#31]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

Currently, acres are always converted to km^2 (1 acre = 0.00404686 km ^2)
**Enhancement request:** Acres should be converted to km^2, hectares, or m^2 (preferring to use the largest unit possible without using decimal places)
See [conversion_helper.js](https://github.com/cannawen/metric_units_reddit_bot/blob/master/src/conversion_helper.js) to get started

**Recommended skills:** Basic javascript
**Estimated time:** 30 minutes

Comment below if you would like to take on this task!

**Comment by JuanPotato** [comment]
I'll take this on

**Comment by cannawen** [comment]
Sweet! Let me know if you need any help!
P.S. I love your username

**Comment by JuanPotato** [comment]
You want it just to be m^2 or hectares and never use km^2?

**Comment by cannawen** [comment]
km^2 should still be used for values of over 1 km^2. Sorry the story was unclear, I'll edit it now!
