### ISSUE TITLE
"bushels" should be converted to metric weights

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#32]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

**Enhancement request:** "bushels" should be converted to metric weights. 
See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion

**Recommended skills:** Basic javascript & basic regular expressions
**Estimated time:** 30 minutes

Comment below if you would like to take on this task!

**Comment by MFogleman** [comment]
I'll take this on

**Comment by cannawen** [comment]
Great, thank you! Let me know if you need any assistance :)
