### ISSUE TITLE
"mr.? bot"

### ISSUE THREAD

**Issue by airbreather** [cannawen/metric_units_reddit_bot#4]
In [this regex](https://github.com/cannawen/metric_units_reddit_bot/blob/322e458d3060089bb13b8bf8bfb7169bf40d91de/src/personality.js#L65), it matches "mr.? bot".

The "." matches any character.

In theory, it looks like it could reply to "mrs bot" with "Actually, I prefer the female gender pronoun. Thanks.", which would be kinda funny.

see: https://regex101.com/r/Isy8YX/2

**Comment by cannawen** [comment]
Very valid point, the regex is incorrect. I'll fix it in the next release, thank you for the bug report!
