### ISSUE TITLE
Handling ranges better

### ISSUE THREAD

**Issue by nalinbhardwaj** [cannawen/metric_units_reddit_bot#41]
Currently, the bot handles ranges in a non-intuitive way by displaying each value separately, the current ranges handling can be made much better instead if we process them separately in `findPotentialConversions` and `formatConversion` to do the following:

- Display ranges in comment as ranges in response, for example, `1-2 miles ≈ 1.6-3.2 km`
- Handle many more joining keywords, such as `1 to 2 miles ≈ 1.6 to 3.2 km`, `1 or 2 miles ≈ 1.6 or 3.2 km` and similar.

I think I can work on this(if the changes make sense?)

**Comment by cannawen** [comment]
That would be awesome! Thanks for volunteering :) Let me know if you need any assistance
