### ISSUE TITLE
Allow for k to represent thousand [#151447001]

### ISSUE THREAD

**Issue by nicolasferraro** [cannawen/metric_units_reddit_bot#46]
i.e. 50k miles should be processed to 50000 miles

A quick solution for this would be to add k matching to the number_regex so when we are parsing `50k` we match `50k` instead of `50` like we do currently. We could then either replace the `k` with `000` or cast the string as a number and multiply it by `1000`.

@cannawen What's your opinion on this? Should we also parse numbers like `20.2k` to `20200`?

I would like to work on this.

**Comment by cannawen** [comment]
If you wait for PR #44 to be merged in (some time within the next few days probably), there will be a nice "preprocess comment" method you can use! Yes, I think changing 20.2k to 20200 would make sense :)

Thanks for volunteering to pick up this task!

**Comment by nalinbhardwaj** [comment]
Similarly, it should be easy to add modifiers like `thousand, m, b, mill, billion` and so on. This could also be a good start to adding interpretation of word numbers `fifty five` and so on.

**Comment by cannawen** [comment]
That's a great idea! Maybe once the we get the "preprocess" code in, we could create some separate stories to add those modifiers and word-numbers as well :)

**Comment by cannawen** [comment]
@nalinbhardwaj The preprocess change was just merged in FYI, so the infrastructure should be there for you to start working on this issue

**Comment by nalinbhardwaj** [comment]
@cannawen did you mean to mention @nicoferraro96 ? Isn't this already assigned to him?

**Comment by cannawen** [comment]
MY BAD, yes, sorry!!

**Comment by nicolasferraro** [comment]
@cannawen Cool, I'll start working on it later today!

**Comment by cannawen** [comment]
Hey @nicoferraro96, we have just added a [CONTRIBUTING.md doc](../tree/master/CONTRIBUTING.md), please check it out when you have time! Sections "Etiquette", "Work on an issue" and "Make a PR" are most important
