### ISSUE TITLE
Increase threshold for light seconds conversion

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#47]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

**Enhancement request:** [Light seconds are used too liberally](https://www.reddit.com/r/AutoDIY/comments/749rro/diy_repair_2013_corolla/dnxltx0/?context=3).
Change code so that >2 million miles are converted to light seconds. See [this file](https://github.com/cannawen/metric_units_reddit_bot/blob/master/src/conversion_helper.js) to get started

**Recommended skills:** Basic javascript
**Estimated time:** 20 minutes

Comment below if you would like to take on this task!

**Comment by cmd-kvn** [comment]
I'd like to take this task @cannawen!

**Comment by cannawen** [comment]
Sounds good! Let me know if you need any assistance getting started :)

**Comment by cmd-kvn** [comment]
I appreciate the offer. I do have a beginner's question: it's required to sign up for a Reddit account to do testing? That's the only way to make the `.yaml` file?

**Comment by cannawen** [comment]
Just straight up copy the sample-environment file without changing any values, you don't need a reddit account to run "npm test". I will update the README file to make the instructions more clear :) Thanks!

**Comment by cmd-kvn** [comment]
Wonderful! It's all sorted and I have the ability to test. I'll start my attempt at the code. Thank you!

**Comment by cannawen** [comment]
Oops wait, it looks like someone else already made a PR on this story @cmd-kvn  ... would you like to pick up a [different story](https://www.pivotaltracker.com/n/projects/2091572#)? Sorry I didn't notice this earlier (it's hard to keep track with all the stories and PRs flying around), there's definitely some process improvements needed.

**Comment by cmd-kvn** [comment]
I appreciate the update and I understand, @cannawen. I'll just check in on the issues when I have time and try my luck again.

**Comment by cannawen** [comment]
@cmd-kvn I added a whole bunch of new issues (not tagged hacktoberfest yet) if you are still interested in contributing :) Again, sorry for the confusion! I'm working on [writing out the project's processes](https://github.com/cannawen/metric_units_reddit_bot/issues/50) so this won't happened again in the future

**Comment by cmd-kvn** [comment]
@cannawen you are bomb.com. I would be happy to take a look!
