### ISSUE TITLE
Keywords that should be trigger a "fl oz" translation instead of "oz"

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#54]
Related to #43 and #52 

Missing: "cup", "breastfeeding", "cans", "tall boy", "brew"

**Comment by cannawen** [comment]
Ah, I shouldn't have closed this. Of course there is more.

"pint", "bartending", "Flow improver", medium, paint, retarder, thinner, primer, wash, acrylic, paste, oil,

**Comment by ajripley** [comment]
Is this still available to fix? I didn't see changes addressing "pint" and "bartending" in the main branch or in any of the pull requests. I'd love to give it a shot, if it's up for grabs. :)

**Comment by nalinbhardwaj** [comment]
@ajripley yep, feel free to make a PR adding the two words. :)

**Comment by ajripley** [comment]
@nalinbhardwaj I assumed that there would be more work - are there no tests for this that would need updating?

I suppose if it's that simple, it should probably go to someone who hasn't made a pull request before.

**Comment by nalinbhardwaj** [comment]
@ajripley the issue will probably be kept open for a while as there'll be more keywords we'd be missing.
