### ISSUE TITLE
Feet per second values should be converted to metric speed

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#55]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

**Current behaviour:**
mph is translated to metric speed, but feet per second is not

**Enhancement request:**
Feet per second values should be translated to metric speed
See [this commit](https://github.com/cannawen/metric_units_reddit_bot/pull/49/files) for an example of how to add a new conversion

**Recommended skills:**
Basic javascript & basic regular expressions

**Estimated effort:** 
30 minutes

# Comment below if you would like to take on this task!

**Comment by esclear** [comment]
I can take this on.

Although I'm not quite sure, if there are common abbreviations for “feet per second”, since __fps__ would also match “frames per second”. But we could use “fps” as a weak indicator and possibly ignore it on gaming-related subreddits?

**Comment by nalinbhardwaj** [comment]
@esclear I highly doubt anyone uses FPS to refer to feet per second. IMO, it’s best to exclude it completely.

**Comment by cannawen** [comment]
@esclear Assigning to you :)

I would probably avoid fps, there's a very high chance of that going wrong.

But if you feel like it's worth a shot to try to add gaming/computer keyword exceptions, we can release it into the wild (for like an hour) and see how it performs? You might have to accept it as wasted code if the test doesn't go well though, but I'm willing to run the experiment if you feel like it makes sense (even if it doesn't work, I'm sure all the gamers will get a laugh out of it)

Edit: [wikipedia](https://en.wikipedia.org/wiki/Foot_per_second) suggests also `ft/s` and `ft/sec`. And of course there are all the possible text combinations of `feet per second`, `ft a sec`, etc. etc.

**Comment by esclear** [comment]
Seems like `ft/sec` is actually being used in the wild.

**Comment by cannawen** [comment]
@esclear FYI we have just added a [CONTRIBUTING.md doc](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md), please check it out when you have time! Sections "Etiquette", "Work on an issue" and "Make a PR" are most important
