### ISSUE TITLE
Add test coverage statistics to repository

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#56]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

**Enhancement request:**
Investigate how to get test coverage data into the README.md file. 
One possible solution is to use [Coveralls](https://coveralls.io/). Any other suggestions are welcome.

**Recommended reading:**
[CONTRIBUTING.md](https://github.com/cannawen/metric_units_reddit_bot/blob/master/CONTRIBUTING.md) (sections "Etiquette", "Work on an issue" and "Make a PR" are most important)

**Estimated effort:** 
30-60 minutes

# Comment below if you would like to take on this task!

**Comment by chazzlabs** [comment]
I'm going to take a look at this one.
