### ISSUE TITLE
Create personality response for "ok/mediocre/meh bot"

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#6]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion. What makes it sassy? The bot sometimes replies to comments like "good bot" and "bad bot" with its personality module.

This story is to give the bot even more personality! It should also reply to comments like "ok bot" or "mediocre bot".

Possible replies:
`/shrug, I'll take it`
`That's just like, your opinion, man`
...and anything else you feel is appropriate

See [personality.js](../tree/master/src/personality.js) and [personality-test.js](../tree/master/test/personality-test.js) to get started

**Comment by fbontin** [comment]
I'll give this a try for hacktoberfest :-)

**Comment by cannawen** [comment]
Sounds good! Let me know if you need any help.
