### ISSUE TITLE
Convert furlong to metric distance

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#7]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion.

Furlongs should be converted to metric distances (meters, km, etc.)

See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion

**Comment by esclear** [comment]
Consider this done :)

**Comment by cannawen** [comment]
Awesome, let me know if you need any help!
