### ISSUE TITLE
Convert nautical miles to km

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#8]
[metric_units](https://www.reddit.com/user/metric_units) is a sassy reddit bot that finds imperial units, and replies with a metric conversion. 

Nautical miles should be converted to metric distances (meters, km, etc.)

See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion

**Comment by seandgrimes** [comment]
Hi Canna, any problem with me picking this issue up?

**Comment by cannawen** [comment]
Go for it! Let me know if you need any assistance :)

**Comment by cannawen** [comment]
Hey @munumafia, it's October! Friendly reminder to re-submit your PR whenever you get a chance :)
