### ISSUE TITLE
Ignore all nba subreddits for mpg

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#81]
** Potential first timers only story - needs more description **

mpg means minutes per game, and the basketball fans are very unhappy. 

Similar fix to #39 , ignore all nba team names from "mpg" conversion

**Comment by cmd-kvn** [comment]
when this is ready I'd like to take an attempt!

**Comment by cannawen** [comment]
Okie dokie! If you have an idea of how to go about doing it, you can feel free to start. 

I was just going to add more detailed first timer instructions so they do not need to leave the page to see how to set up the project, etc., It's just blocked on me not having enough time to do this :P haha. You can browse the readme and other documentation to find all the info you need

You can also wait like... Maybe 24-48 hours for me to fill out the story more if you wish. Up to you!

**Comment by cannawen** [comment]
Assigning to @cmd-kvn

**Comment by cmd-kvn** [comment]
I'm slightly confused - the issue requests to ignore NBA subreddits while the comment requests to ignore NBA team names. Some NBA subreddits don't follow the team name e.g. Trail Blazers !== r/ripcity. The glossary/comment for ignoredKeywords doesn't give me a better idea which way to go. Currently I have team name, not subreddit name, ignored. How can I help you fix the issue properly?

**Comment by chazzlabs** [comment]
It appears that you need the subreddit name, not the team name, in the `ignoredKeywords` array.  I agree it's a bit ambiguous.

**Comment by cmd-kvn** [comment]
@chazzlabs thanks for your assistance! I'll go ahead with the subreddit name list and ready a PR. Before that, would you or @cannawen be so kind to add a `hacktoberfest` label?

**Comment by chazzlabs** [comment]
@cmd-kvn Added the `hacktoberfest` label.  But don't worry if the issues you're resolving aren't marked with that label; any PR you make during October will count regardless.

**Comment by cannawen** [comment]
> It appears that you need the subreddit name, not the team name, in the ignoredKeywords array. I agree it's a bit ambiguous.

I'm sorry, the issue was not fully ready 😭 😭 😭

**Comment by chazzlabs** [comment]
> I'm sorry, the issue was not fully ready 😭 😭 😭

Sorry! 😦

**Comment by cannawen** [comment]
Haha, don't worry, I'm just kidding :)
