### ISSUE TITLE
Ignore "cup" measurements over 100

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#82]
Modify `isWeaklyInvalidInput()` of `cups` to ignore cup measurements over 100. You can read documentation of the function [here](https://github.com/cannawen/metric_units_reddit_bot/blob/master/src/conversion_helper.js#L120) and the line to be changed is [this](https://github.com/cannawen/metric_units_reddit_bot/blob/master/src/conversion_helper.js#L432).

Add tests as well to ensure this works.

## Related links
[Reddit comment](https://www.reddit.com/r/metric_units/comments/73edn2/constructive_feedback_thread/do2sf39/)

**Comment by nalinbhardwaj** [comment]
@cannawen updated to include details.

**Comment by jacobScottAllen** [comment]
I would like to work on this!
