### ISSUE TITLE
Feature request: Convert lbs/inch to kg/mm and N/m

### ISSUE THREAD

**Issue by nalinbhardwaj** [cannawen/metric_units_reddit_bot#83]
## Issue description

lbs/inch should be converted to kg/mm and N/m, these are units for spring rate forces, surface tension etc.

## Recommended skills

Basic javascript & basic regular expressions

## Relevant Links
[Reddit comment](https://www.reddit.com/r/metric_units/comments/73edn2/constructive_feedback_thread/do3ueey/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=metric_units)

**Estimated time**: 30 minutes

Comment below if you would like to take on this task!

**Comment by Skuhoo** [comment]
I'll take this task!

**Comment by nalinbhardwaj** [comment]
Great, thanks @Skuhoo

**Comment by nalinbhardwaj** [comment]
Hey @Skuhoo, with the added feedback in the Reddit thread, I've updated the issue description, please check it out.

**Comment by Skuhoo** [comment]
@nalinbhardwaj Alright, noted.
