### ISSUE TITLE
Convert acres to km^2

### ISSUE THREAD

**Issue by cannawen** [cannawen/metric_units_reddit_bot#9]
Acres should be converted to km^2

See [this commit](../commit/e0eb7f637d8703c9251de70794d117438f9d8fe1) for an example of how to add a new conversion

**Comment by annuhdo** [comment]
Hi! I’ll work on this for Hacktoberfest :)

**Comment by cannawen** [comment]
Sure, sounds good!

**Comment by devesh-verma** [comment]
@cannawen  I would like to work on this if there's no progress?

**Comment by cannawen** [comment]
@devshiva619 , The issue has already been assigned, but you can work on a new (similar) feature if you want! I'll tag you in it.
